### ISSUE TITLE
Add support for the bufferline.

### ISSUE THREAD

**Issue by jasper-schnabel** [jandamm/cryoline.nvim#1]
Hey!

Thanks for the very cool plugin, I like the simplicity and how I was able to create a awesome statusline with just a few lines of code.

I was wondering if something similarly simple could be achieved for a bufferline as well. Without having to write many lines of code. I don't know how difficult it is to implement something like this, but it would be nice to have such an option.

Feel free to close this issue if it is against the idea of this plugin.

Thanks

**Comment by jandamm** [comment]
Hey @jasper-schnabel,

thanks for your interest in Cryoline.

I'm not opposed to the idea of supporting the tabline as well.
But I'm not sure how the api should look like.

There are two concepts of the tabline. The one that ships with vim and the other which is called bufferline and is similar to what other editors ship with.

Cryoline makes it easy to provide a statusline for each filetype.
What should this look like for the tabline? Should it change for filetype? Should it just change the current tab (or buffer) or for the whole line?

Also there is no default implementation for the tabline component. So the whole tabs have to be created manually.

Everything I can think of would require providing a "fixed" structure of the tabline.
Or the context would just provide number of tabs + number of buffers in the tab. But this would require much more work in the user functions since they would have to recreate the tabs themselves.

Have you had a look at https://github.com/rafcamlet/tabline-framework.nvim? I'm not using it but thought about migrating.

**Comment by jasper-schnabel** [comment]
Thank you for the quick response. 

From this point of view, it is of course not very useful and smart to implement a tab/bufferline within cryoline.nvim. It would probably also not be very user friendly and would bloat cryoline.

Thanks for the suggestion with  https://github.com/rafcamlet/tabline-framework.nvim, I will try it out.

And again, really nice plugin.
Thanks.
